# Generated by Django 4.2.7 on 2023-12-03 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('JUNIOR SECONDARY 1', 'Class1'), ('JUNIOR SECONDARY 2', 'Class2'), ('JUNIOR SECONDARY 3', 'Class3'), ('SENIOR SECONDARY SCHOOL 1', 'Class4'), ('SENIOR SECONDARY SCHOOL 2', 'Class5'), ('SENIOR SECONDARY SCHOOL 3', 'Class6')], max_length=30)),
                ('code', models.CharField(choices=[('JSS 1', 'Class Code1'), ('JSS 2', 'Class Code2'), ('JSS 3', 'Class Code3'), ('SSS 1', 'Class Code4'), ('SSS 2', 'Class Code5'), ('SSS 3', 'Class Code6')], max_length=10)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('min_mark', models.PositiveIntegerField(default=40)),
                ('mark_obtained', models.PositiveIntegerField(default=0, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned_subjects', models.ManyToManyField(related_name='teachers', to='core.subject')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom')),
                ('enrolled_subjects', models.ManyToManyField(related_name='enrolled_students', to='core.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
