# Generated by Django 4.2.7 on 2023-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JSS 1", "Jss 1"),
                    ("JSS 2", "Jss 2"),
                    ("JSS 3", "Jss 3"),
                    ("SSS 1", "Sss 1"),
                    ("SSS 2", "Sss 2"),
                    ("SSS 3", "Sss 3"),
                ],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="title",
            field=models.CharField(
                choices=[
                    ("JUNIOR SECONDARY SCHOOL 1", "Junior Secondary School 1"),
                    ("JUNIOR SECONDARY SCHOOL 2", "Junior Secondary School 2"),
                    ("JUNIOR SECONDARY SCHOOL 3", "Junior Secondary School 3"),
                    ("SENIOR SECONDARY SCHOOL 1", "Senior Secondary School 1"),
                    ("SENIOR SECONDARY SCHOOL 2", "Senior Secondary School 2"),
                    ("SENIOR SECONDARY SCHOOL 3", "Senior Secondary School 3"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
