# Generated by Django 4.2.7 on 2023-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(
                choices=[
                    ("ENGLISH LANGUAGE", "English Language"),
                    ("MATHEMATICS", "Mathematics"),
                    ("AGRICULTURAL SCIENCE", "Agricultural Science"),
                    ("BIOLOGY", "Biology"),
                    ("ECONOMICS", "Economics"),
                    ("CIVIC EDUCATION", "Civic Education"),
                    ("FRENCH LANGUAGE", "French"),
                    ("FURTHER MATHEMATICS", "Further Mathematics"),
                    ("CHEMISTRY", "Chemistry"),
                    ("PHYSICS", "Physics"),
                    ("GEOGRAPHY", "Geography"),
                    ("COMPUTER SCIENCE", "Computer Science"),
                    ("SOCIAL STUDIES", "Social Studies"),
                    ("MUSIC", "Music"),
                    ("GOVERNMENT", "Government"),
                    ("COMMERCE", "Commerce"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("title", "code", "class_room")},
        ),
    ]
